# Write a Python Program to Add Two Matrices.

In [15]:
import numpy as np
A = np.random.randint(1,20,(4,4))
B = np.random.randint(1,20,(4,4))
print("A : ",A)
print("B : ",B)
print("Sum of two matrices is : ",A+B)

A :  [[13 14 10  2]
 [15 11  6 17]
 [ 8 13 18  9]
 [ 9  5  9  8]]
B :  [[ 3 18 17  2]
 [ 7 18  5  3]
 [12  9 17 15]
 [13  2  6 18]]
Sum of two matrices is :  [[16 32 27  4]
 [22 29 11 20]
 [20 22 35 24]
 [22  7 15 26]]


# Write a Python Program to Multiply Two Matrices.

In [18]:
C = np.random.randint(1,20,(4,4))
D = np.random.randint(1,20,(4,4))
print("C : ",C)
print("D : ",D)
print("Multiplication of two matrices is : ",C*D)

C :  [[18  7  6  9]
 [16  4 19 19]
 [12 15 15  3]
 [ 5 14 17 18]]
D :  [[14 16 18 13]
 [14  7  6 12]
 [10  1 18  5]
 [17  1 11  1]]
Multiplication of two matrices is :  [[252 112 108 117]
 [224  28 114 228]
 [120  15 270  15]
 [ 85  14 187  18]]


# Write a Python Program to Transpose a Matrix.

In [20]:
mat = np.random.randint(1,100,(3,3))
print("Matrix is : ",mat)
print("Transpose of the matrix is : ",mat.T)

Matrix is :  [[69 54 52]
 [16 31 24]
 [43 38 85]]
Transpose of the matrix is :  [[69 16 43]
 [54 31 38]
 [52 24 85]]


# Write a Python Program to Sort Words in Alphabetic Order.

In [40]:
l = input("Enter the string : ")
l = l.split(' ')
l.sort(key = lambda v : v.upper())
str = " "
l = str.join(l)
print("Strig is : ",l)


Enter the string : Write a Python Program to Sort Words in Alphabetic Order
Strig is :  a Alphabetic in Order Program Python Sort to Words Write


# Write a Python Program to Remove Punctuation From a String.

In [59]:
string = input("Enter your string : ")
print(string.replace('!',''))


Enter your string : Wr!ite a! Pyth!on ! Pro!gram to Remo!ve Pun!ctuation From a ! Stri!ng
Write a Python  Program to Remove Punctuation From a  String
